[package]
name = "tauri-plugin-plauth"
version = "1.0.2"
authors = ["Phuc Le <lecaobaophuc@gmail.com>"]
description = "Tauri plugin for authentication (PLAUTH) supporting macOS and iOS platforms with ASWebAuthenticationSession"
license = "MIT"
repository = "https://github.com/lecaobaophuc0912/tauri-plugin-plauth"
homepage = "https://github.com/lecaobaophuc0912/tauri-plugin-plauth"
documentation = "https://github.com/lecaobaophuc0912/tauri-plugin-plauth"
keywords = ["tauri", "plugin", "auth", "macos", "ios"]
categories = ["api-bindings", "gui", "web-programming"]
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-plauth"

[dependencies]
tauri = { version = "2.7.0" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
tauri-swift-runtime = "0.1.2"

[build-dependencies]
tauri-plugin = { version = "2.3.1", features = ["build"] }
swift-rs = { version = "1.0.7", features = ["build"] }
